name: Merge branch to master

# on:
#   pull_request_target:
#     types:
#       - closed

on:
  push:
    branches:
      - "test-branch"

jobs:
  if_merged:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get PR branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      - name: Get the list of all Lokalise branches
        run: |
          > lokaliseBranches.json curl --location --request GET 'https://api.lokalise.com/api2/projects/4204698362972bb02dc737.79420570/branches' \
            --header 'x-api-token: ${{ secrets.LOKALISE_ACCESS_TOKEN }}'

      - name: file
        run: cat ./lokaliseBranches.json

      - name: Get current branch id on Lokalise
        id: branch-id
        run: echo "::set-output name=current_branch::$(jq -r --arg queryname "${{ steps.branch-name.outputs.current_branch }}" '.branches[] | select(.name == $queryname).branch_id' lokaliseBranches.json)"

      - name: Hellp
        run: echo "${{ steps.branch-id.outputs.current_branch }}"

      - name: Merge current branch on mastery branch
        run: |
          curl --location --request POST 'https://api.lokalise.com/api2/projects/4204698362972bb02dc737.79420570/branches/${{ steps.branch-id.outputs.current_branch }}/merge' \
          --header 'content-type: application/json' \
          --header 'x-api-token: ${{ secrets.LOKALISE_ACCESS_TOKEN }}'
