name: Merge branch to master

on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get PR branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      - name: Get the list of all Lokalise branches
        run: |
          > lokaliseBranches.json curl --location --request GET 'https://api.lokalise.com/api2/projects/4204698362972bb02dc737.79420570/branches' \
            --header 'x-api-token: ${{ secrets.LOKALISE_ACCESS_TOKEN }}'

      - name: Get current branch id from Lokalise
        id: branch-id
        run: echo "::set-output name=current_branch::$(jq -r --arg queryname "${{ steps.branch-name.outputs.head_ref_branch }}" '.branches[] | select(.name == $queryname).branch_id' lokaliseBranches.json)"

      - name: Merge Lokalise current branch on Lokalise master branch
        run: |
          curl --location --request POST 'https://api.lokalise.com/api2/projects/4204698362972bb02dc737.79420570/branches/${{ steps.branch-id.outputs.current_branch }}/merge' \
          --header 'content-type: application/json' \
          --header 'x-api-token: ${{ secrets.LOKALISE_ACCESS_TOKEN }}'

      - name: Delete Lokalise branch after merge
        run: |
          curl --location --request DELETE 'https://api.lokalise.com/api2/projects/4204698362972bb02dc737.79420570/branches/${{ steps.branch-id.outputs.current_branch }}' \
          --header 'x-api-token: ${{ secrets.LOKALISE_ACCESS_TOKEN }}'
