name: Merge branch to master

# on:
#   pull_request_target:
#     types:
#       - closed

on:
  push:
    branches:
      - "merge"

jobs:
  if_merged:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get PR branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      - name: Get the list of all Lokalise branches
        run: |
          > lokaliseBranches.json curl --location --request GET 'https://api.lokalise.com/api2/projects/4204698362972bb02dc737.79420570/branches' \
            --header 'x-api-token: ${{ secrets.LOKALISE_ACCESS_TOKEN }}'

      - name: Get current branch id on Lokalise
        id: branch-id
        run: jq -r --arg queryname "${{ steps.branch-name.outputs.current_branch }}" '.branches[] | select(.name == $queryname).branch_id' lokaliseBranches.json

      - name: Check result
        run: echo "${{ steps.branch-id.outputs }}"
